spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmanager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8080

mail:
    host: smtp.qq.com
    port: 587
    username: 3342931517@qq.com
    password: zisauwuyccxjdaea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true